// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentMicro.Infrastructure.Contexts;

namespace RentMicro.Infrastructure.Migrations
{
    [DbContext(typeof(RentContext))]
    partial class RentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RentMicro.Domain.RentAggregate.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.HasKey("Id");

                    b.ToTable("Rents");
                });

            modelBuilder.Entity("RentMicro.Domain.RentAggregate.RentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EndDate");

                    b.Property<string>("InitialDate");

                    b.Property<int>("Quantity");

                    b.Property<Guid?>("RentId");

                    b.Property<decimal>("UnitPrice");

                    b.HasKey("Id");

                    b.HasIndex("RentId");

                    b.ToTable("RentItem");
                });

            modelBuilder.Entity("RentMicro.Domain.RentAggregate.RentItem", b =>
                {
                    b.HasOne("RentMicro.Domain.RentAggregate.Rent", "Rent")
                        .WithMany("RentItens")
                        .HasForeignKey("RentId");
                });
#pragma warning restore 612, 618
        }
    }
}
